### PR TITLE
deps: updated gin-gonic from 1.6.3 to 1.7.7;

### PR DESCRIPTION
**Pull request by ss89**

### CODE REVIEW

**Review by j4k4 — APPROVED** [review]
+1

**Comment by applike-ss** [comment]
We can't merge this yet, because i found an issue that was introduced in gin 1.7.0 which does add a constraint under which circumstances the headers for client ip determination are trusted. Gin supposes one to use the .Run func to start it, however we currently don't make use of that.

**Comment by applike-ss** [comment]
This issue is about the breaking change they did: https://github.com/gin-gonic/gin/issues/2697

Their project management seems a bit strange, because their master does contain the fix and on top of it is version v1.7.3, however the tag v1.7.3 does NOT include the fix

**Comment by applike-ss** [comment]
finally gin-gonic 1.7.7 release did fix our issue, so checking it with our apps and will merge afterwards

**Pull request merged**
